// this file is generated by the build script by
// listing all the tests in the tests repository
// This file can be edited to manually change the
// order of the tests or limit the tests to a subset
// Just note that this file is loaded as soon as the
// world starts. Editing afterwards will have no effect.
testsManifest = [];

