cp -r ../Fizzygum.org-website/minimal-mistakes/staticman.yml .
cp -r ../Fizzygum.org-website/minimal-mistakes/Rakefile .
cp -r ../Fizzygum.org-website/minimal-mistakes/package.json .
cp -r ../Fizzygum.org-website/minimal-mistakes/minimal-mistakes-jekyll.gemspec .
cp -r ../Fizzygum.org-website/minimal-mistakes/Gemfile.lock .
cp -r ../Fizzygum.org-website/minimal-mistakes/Gemfile .
cp -r ../Fizzygum.org-website/minimal-mistakes/banner.js .
cp -r ../Fizzygum.org-website/minimal-mistakes/assets .
cp -r ../Fizzygum.org-website/minimal-mistakes/_sass .
cp -r ../Fizzygum.org-website/minimal-mistakes/_posts .
cp -r ../Fizzygum.org-website/minimal-mistakes/_pages .
cp -r ../Fizzygum.org-website/minimal-mistakes/_layouts .
cp -r ../Fizzygum.org-website/minimal-mistakes/_includes .
cp -r ../Fizzygum.org-website/minimal-mistakes/_drafts .
cp -r ../Fizzygum.org-website/minimal-mistakes/_docs .
cp -r ../Fizzygum.org-website/minimal-mistakes/_data .
cp -r ../Fizzygum.org-website/minimal-mistakes/_config.yml .
