cp -r ../minimal-mistakes-fork/favicon.ico .
cp -r ../minimal-mistakes-fork/staticman.yml .
cp -r ../minimal-mistakes-fork/Rakefile .
cp -r ../minimal-mistakes-fork/package.json .
cp -r ../minimal-mistakes-fork/minimal-mistakes-jekyll.gemspec .
cp -r ../minimal-mistakes-fork/Gemfile.lock .
cp -r ../minimal-mistakes-fork/Gemfile .
cp -r ../minimal-mistakes-fork/banner.js .
cp -r ../minimal-mistakes-fork/assets .
cp -r ../minimal-mistakes-fork/_sass .
cp -r ../minimal-mistakes-fork/_posts .
cp -r ../minimal-mistakes-fork/_pages .
cp -r ../minimal-mistakes-fork/_layouts .
cp -r ../minimal-mistakes-fork/_includes .
cp -r ../minimal-mistakes-fork/_drafts .
cp -r ../minimal-mistakes-fork/_docs .
cp -r ../minimal-mistakes-fork/_data .
cp -r ../minimal-mistakes-fork/_config.yml .
