cp -r ../minimal-mistakes-fork-for-fizzygum-site/favicon.ico .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/staticman.yml .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/Rakefile .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/package.json .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/minimal-mistakes-jekyll.gemspec .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/Gemfile.lock .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/Gemfile .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/banner.js .
rm -rf assets
cp -r ../minimal-mistakes-fork-for-fizzygum-site/assets .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_sass .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_posts .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_pages .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_layouts .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_includes .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_drafts .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_docs .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_data .
cp -r ../minimal-mistakes-fork-for-fizzygum-site/_config.yml .
