// Generated by CoffeeScript 1.12.7
window.GenericPanelIconWdgt_coffeSource = 'class GenericPanelIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new GenericPanelIconAppearance @\n\n\n';
