// Generated by CoffeeScript 1.12.7
window.ItalicIconWdgt_coffeSource = 'class ItalicIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ItalicIconAppearance @\n\n\n';
