// Generated by CoffeeScript 1.12.7
window.WelcomeIconWdgt_coffeSource = 'class WelcomeIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new WelcomeIconAppearance @\n\n\n';
