// Generated by CoffeeScript 1.12.7
window.AlignLeftIconWdgt_coffeSource = 'class AlignLeftIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new AlignLeftIconAppearance @\n\n\n';
