// Generated by CoffeeScript 1.12.7
window.CFDegreesConverterIconWdgt_coffeSource = 'class CFDegreesConverterIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new CFDegreesConverterIconAppearance @\n\n';
