// Generated by CoffeeScript 1.12.7
window.ClippingBoxMorph_coffeSource = '# REQUIRES ClippingAtRectangularBoundsMixin\n\n# I can have an optionally rounded border\n\nclass ClippingBoxMorph extends BoxMorph\n\n  @augmentWith ClippingAtRectangularBoundsMixin\n\n';
