// Generated by CoffeeScript 1.12.7
window.ArrowEIconWdgt_coffeSource = 'class ArrowEIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ArrowEIconAppearance @\n\n\n';
