// Generated by CoffeeScript 1.12.7
window.ColorPalettePatchProgrammingIconWdgt_coffeSource = 'class ColorPalettePatchProgrammingIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ColorPalettePatchProgrammingIconAppearance @\n\n';
