// Generated by CoffeeScript 1.12.7
window.MapPinIconWdgt_coffeSource = 'class MapPinIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new MapPinIconAppearance @\n    @toolTipMessage = "map pin"\n';
