// Generated by CoffeeScript 1.12.7
window.PaintBucketIconWdgt_coffeSource = 'class PaintBucketIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new PaintBucketIconAppearance @\n\n\n';
