// Generated by CoffeeScript 1.12.7
window.TextIconWdgt_coffeSource = 'class TextIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new TextIconAppearance @\n\n\n';
