// Generated by CoffeeScript 1.12.7
window.UncollapsedStateIconMorph_coffeSource = 'class UncollapsedStateIconMorph extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new UncollapsedStateIconAppearance @\n';
