// Generated by CoffeeScript 1.12.7
window.ArrowSWIconWdgt_coffeSource = 'class ArrowSWIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ArrowSWIconAppearance @\n\n\n';
