// Generated by CoffeeScript 1.12.7
window.ArrowNIconWdgt_coffeSource = 'class ArrowNIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ArrowNIconAppearance @\n\n\n';
