// Generated by CoffeeScript 1.12.7
window.FizzygumLogoIconWdgt_coffeSource = 'class FizzygumLogoIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new FizzygumLogoIconAppearance @\n\n';
