// Generated by CoffeeScript 1.12.7
window.ScatterPlotIconWdgt_coffeSource = 'class ScatterPlotIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ScatterPlotIconAppearance @\n\n\n';
