// Generated by CoffeeScript 1.12.7
window.VideoPlayButtonWdgt_coffeSource = 'class VideoPlayButtonWdgt extends ExternalLinkButtonWdgt\n\n  constructor: (@color) ->\n    super\n    @appearance = new VideoPlayIconAppearance @\n\n\n';
