// Generated by CoffeeScript 1.12.7
window.BarPlotIconWdgt_coffeSource = 'class BarPlotIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new BarPlotIconAppearance @\n\n\n';
