// Generated by CoffeeScript 1.12.7
window.BoldIconWdgt_coffeSource = 'class BoldIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new BoldIconAppearance @\n\n\n';
