// Generated by CoffeeScript 1.12.7
window.CalculatingNodeIconWdgt_coffeSource = 'class CalculatingNodeIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new CalculatingNodeIconAppearance @\n\n\n';
