// Generated by CoffeeScript 1.12.7
window.PreferredSize_coffeSource = '# PreferredSize\n# ...just giving some convenient names to constants/singletons\n\nclass PreferredSize\n\n  @THIS_ONE_I_HAVE_NOW: -1\n  @DONT_MIND: -2\n';
