// Generated by CoffeeScript 1.12.7
window.ScooterIconMorph_coffeSource = 'class ScooterIconMorph extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ScooterIconAppearance @\n';
