// Generated by CoffeeScript 1.12.7
window.ShortcutArrowIconWdgt_coffeSource = 'class ShortcutArrowIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ShortcutArrowIconAppearance @\n\n\n';
