// Generated by CoffeeScript 1.12.7
window.ArrowSIconWdgt_coffeSource = 'class ArrowSIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ArrowSIconAppearance @\n\n\n';
