// Generated by CoffeeScript 1.12.7
window.DashboardsIconWdgt_coffeSource = 'class DashboardsIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new DashboardsIconAppearance @\n\n\n';
