// Generated by CoffeeScript 1.12.7
window.FizzygumLogoWithTextIconWdgt_coffeSource = 'class FizzygumLogoWithTextIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new FizzygumLogoWithTextIconAppearance @\n\n';
