// Generated by CoffeeScript 1.12.7
window.FloppyDiskIconWdgt_coffeSource = 'class FloppyDiskIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new FloppyDiskIconAppearance @\n\n\n';
