// Generated by CoffeeScript 1.12.7
window.SimpleUSAMapIconWdgt_coffeSource = 'class SimpleUSAMapIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new SimpleUSAMapIconAppearance @\n\n\n';
