// Generated by CoffeeScript 1.12.7
window.TypewriterIconWdgt_coffeSource = 'class TypewriterIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new TypewriterIconAppearance @\n\n';
