// Generated by CoffeeScript 1.12.7
window.AlignRightIconWdgt_coffeSource = 'class AlignRightIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new AlignRightIconAppearance @\n\n\n';
