// Generated by CoffeeScript 1.12.7
window.ArrowWIconWdgt_coffeSource = 'class ArrowWIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ArrowWIconAppearance @\n\n\n';
