// Generated by CoffeeScript 1.12.7
window.ArrowSEIconWdgt_coffeSource = 'class ArrowSEIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ArrowSEIconAppearance @\n\n\n';
