// Generated by CoffeeScript 1.12.7
window.BasementIconWdgt_coffeSource = 'class BasementIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new BasementIconAppearance @\n\n\n';
