// Generated by CoffeeScript 1.12.7
window.DestroyIconMorph_coffeSource = 'class DestroyIconMorph extends IconMorph\n\n  colloquialName: ->\n    "\\"Destroy\\" icon"\n\n  constructor: (@color) ->\n    super\n    @appearance = new DestroyIconAppearance @\n    @toolTipMessage = "explosion"\n';
