// Generated by CoffeeScript 1.12.7
window.ElasticWindowIconWdgt_coffeSource = 'class ElasticWindowIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ElasticWindowIconAppearance @\n\n\n';
