// Generated by CoffeeScript 1.12.7
window.ExternalLinkIconWdgt_coffeSource = 'class ExternalLinkIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ExternalLinkIconAppearance @\n\n\n';
