// Generated by CoffeeScript 1.12.7
window.FloraIconMorph_coffeSource = 'class FloraIconMorph extends IconMorph\n\n  colloquialName: ->\n    "Flora icon"\n\n  constructor: (@color) ->\n    super\n    @appearance = new FloraIconAppearance @\n';
