// Generated by CoffeeScript 1.12.7
window.GrayscalePalettePatchProgrammingIconWdgt_coffeSource = 'class GrayscalePalettePatchProgrammingIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new GrayscalePalettePatchProgrammingIconAppearance @\n\n';
