// Generated by CoffeeScript 1.12.7
window.ScratchAreaIconMorph_coffeSource = '# based on https://thenounproject.com/term/organization/153374/\nclass ScratchAreaIconMorph extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ScratchAreaIconAppearance @\n\n\n';
