// Generated by CoffeeScript 1.12.7
window.TextToolbarIconWdgt_coffeSource = 'class TextToolbarIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new TextToolbarIconAppearance @\n\n\n';
