// Generated by CoffeeScript 1.12.7
window.ToolbarsIconWdgt_coffeSource = 'class ToolbarsIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ToolbarsIconAppearance @\n\n\n';
