// Generated by CoffeeScript 1.12.7
window.VaporwaveSunIconWdgt_coffeSource = 'class VaporwaveSunIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new VaporwaveSunIconAppearance @\n\n';
