// Generated by CoffeeScript 1.12.7
window.WindowsToolbarIconWdgt_coffeSource = 'class WindowsToolbarIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new WindowsToolbarIconAppearance @\n\n\n';
