// Generated by CoffeeScript 1.12.7
window.CollapsedStateIconMorph_coffeSource = 'class CollapsedStateIconMorph extends IconMorph\n\n  colloquialName: ->\n    "\\"Collapsed state\\" icon"\n\n  constructor: (@color) ->\n    super\n    @appearance = new CollapsedStateIconAppearance @\n\n';
