// Generated by CoffeeScript 1.12.7
window.FolderIconWdgt_coffeSource = 'class FolderIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new FolderIconAppearance @\n\n\n';
