// Generated by CoffeeScript 1.12.7
window.FormatAsCodeIconWdgt_coffeSource = 'class FormatAsCodeIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new FormatAsCodeIconAppearance @\n\n\n';
