// Generated by CoffeeScript 1.12.7
window.RasterPicIconWdgt_coffeSource = 'class RasterPicIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new RasterPicIconAppearance @\n\n\n';
