// Generated by CoffeeScript 1.12.7
window.ScriptIconWdgt_coffeSource = 'class ScriptIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ScriptIconAppearance @\n\n\n';
