// Generated by CoffeeScript 1.12.7
window.TemplatesIconWdgt_coffeSource = 'class TemplatesIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new TemplatesIconAppearance @\n\n\n';
