// Generated by CoffeeScript 1.12.7
window.VaporwaveBackgroundIconWdgt_coffeSource = 'class VaporwaveBackgroundIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new VaporwaveBackgroundIconAppearance @\n\n';
