// Generated by CoffeeScript 1.12.7
window.VideoPlayIconWdgt_coffeSource = 'class VideoPlayIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new VideoPlayIconAppearance @\n\n\n';
