// Generated by CoffeeScript 1.12.7
window.Grid3D_coffeSource = '# REQUIRES DeepCopierMixin\n\nclass Grid3D\n\n  @augmentWith DeepCopierMixin\n\n  width: nil\n  height: nil\n  vertexIndexes: nil\n   \n  constructor: (@width, @height, @vertexIndexes = []) ->\n';
