// Generated by CoffeeScript 1.12.7
window.PatchProgrammingIconWdgt_coffeSource = 'class PatchProgrammingIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new PatchProgrammingIconAppearance @\n\n\n';
