// Generated by CoffeeScript 1.12.7
window.PlaneGrid3D_coffeSource = '# REQUIRES DeepCopierMixin\n\nclass PlaneGrid3D\n\n  @augmentWith DeepCopierMixin\n\n  width: nil\n  height: nil\n  vertexIndexes: nil\n   \n  constructor: (@width, @height, @vertexIndexes = []) ->\n';
