// Generated by CoffeeScript 1.12.7
window.SimpleWorldMapIconWdgt_coffeSource = 'class SimpleWorldMapIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new SimpleWorldMapIconAppearance @\n\n\n';
