// Generated by CoffeeScript 1.12.7
window.WidgetIconWdgt_coffeSource = 'class WidgetIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new WidgetIconAppearance @\n\n\n';
