// Generated by CoffeeScript 1.12.7
window.ChangeFontIconWdgt_coffeSource = 'class ChangeFontIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ChangeFontIconAppearance @\n\n';
