// Generated by CoffeeScript 1.12.7
window.DegreesConverterNodeIconWdgt_coffeSource = 'class DegreesConverterIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new DegreesConverterIconAppearance @\n\n\n';
