// Generated by CoffeeScript 1.12.7
window.EmptyWindowIconWdgt_coffeSource = 'class EmptyWindowIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new EmptyWindowIconAppearance @\n\n\n';
