// Generated by CoffeeScript 1.12.7
window.IncreaseFontSizeIconWdgt_coffeSource = 'class IncreaseFontSizeIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new IncreaseFontSizeIconAppearance @\n\n\n';
