// Generated by CoffeeScript 1.12.7
window.InternalIconMorph_coffeSource = 'class InternalIconMorph extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new InternalIconAppearance @\n';
