// Generated by CoffeeScript 1.12.7
window.SlidesToolbarIconWdgt_coffeSource = 'class SlidesToolbarIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new SlidesToolbarIconAppearance @\n\n\n';
