// Generated by CoffeeScript 1.12.7
window.SliderNodeCalculatingNodeIconWdgt_coffeSource = 'class SliderNodeIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new SliderNodeIconAppearance @\n\n\n';
