// Generated by CoffeeScript 1.12.7
window.WindowWithScrollingPanelIconWdgt_coffeSource = 'class WindowWithScrollingPanelIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new WindowWithScrollingPanelIconAppearance @\n\n\n';
