// Generated by CoffeeScript 1.12.7
window.AllPlotsIconWdgt_coffeSource = 'class AllPlotsIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new AllPlotsIconAppearance @\n\n\n';
