// Generated by CoffeeScript 1.12.7
window.ArrowNWIconWdgt_coffeSource = 'class ArrowNWIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ArrowNWIconAppearance @\n\n\n';
