// Generated by CoffeeScript 1.12.7
window.ExternalIconMorph_coffeSource = 'class ExternalIconMorph extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new ExternalIconAppearance @\n';
