// Generated by CoffeeScript 1.12.7
window.HeartIconMorph_coffeSource = 'class HeartIconMorph extends IconMorph\n\n  colloquialName: ->\n    "Heart icon"\n\n  constructor: (@color) ->\n    super\n    @appearance = new HeartIconAppearance @\n';
