// Generated by CoffeeScript 1.12.7
window.LittleWorldIconWdgt_coffeSource = 'class LittleWorldIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new LittleWorldIconAppearance @\n\n';
