// Generated by CoffeeScript 1.12.7
window.LittleUSAIconWdgt_coffeSource = 'class LittleUSAIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new LittleUSAIconAppearance @\n\n';
