// Generated by CoffeeScript 1.12.7
window.PatchProgrammingComponentsIconWdgt_coffeSource = 'class PatchProgrammingComponentsIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new PatchProgrammingComponentsIconAppearance @\n\n\n';
