// Generated by CoffeeScript 1.12.7
window.Plot3DIconWdgt_coffeSource = 'class Plot3DIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new Plot3DIconAppearance @\n\n\n';
