// Generated by CoffeeScript 1.12.7
window.SimpleSlideIconWdgt_coffeSource = 'class SimpleSlideIconWdgt extends IconMorph\n\n  constructor: (@color) ->\n    super\n    @appearance = new SimpleSlideIconAppearance @\n\n';
