// Generated by CoffeeScript 1.10.0
window.FittingSpecTextInLargerBounds_coffeSource = '# FittingSpecTextInLargerBounds\n\n\nclass FittingSpecTextInLargerBounds\n  @FLOAT: false\n  @SCALEUP: true\n';
